### ISSUE TITLE
mask标记方式

### ISSUE THREAD

**Issue by huaweiboy** [jzm-chairman/sohu2022-nlp-rank1#2]
![image](https://user-images.githubusercontent.com/5070286/206993448-ad8b15b9-9b1f-43c6-b735-1001ed43aaef.png)
这里不同的mask标记方式有何玄机么？貌似并不是论文中简单的【Mask】【实体】  还望大佬解答

**Comment by stack-heap-overflow** [comment]
你好，这里没有什么讲究，都是[MASK]加一个分隔符，只是分隔符可以换不同的形式（没有分隔或者逗号等），另外差别就是XLNet用\<mask\>来表示BERT的[MASK]符号
